### ISSUE TITLE
List of things in the Conductor

### ISSUE THREAD

**Issue by philipbeadle** [holochain/holochain-client-js#1]
I need a list of:
- [ ] App Interfaces 
- [ ] Agents
- [ ] Cells

Cheers

**Comment by Connoropolous** [comment]
@philipbeadle not sure if you know, but there is now `listCellIds`, and `listActiveAppIds` is coming soon

**Comment by Connoropolous** [comment]
https://github.com/holochain/holochain-conductor-api/blob/27c86fd8b0df391f9940c4796b930aea325e7fb6/src/api/admin.ts#L39-L40
