### ISSUE TITLE
libraries depending on this receive build warnings about source maps

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-client-js#115]
WARNING in ../../node_modules/.pnpm/@holochain+client@0.4.3/node_modules/@holochain/client/lib/api/admin/index.js
Module Warning (from ../../node_modules/.pnpm/source-map-loader@3.0.1_webpack@5.67.0/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/x/code/hREA/node_modules/.pnpm/@holochain+client@0.4.3/node_modules/@holochain/client/src/api/admin/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/x/code/hREA/node_modules/.pnpm/@holochain+client@0.4.3/node_modules/@holochain/client/src/api/admin/index.ts'

source map should be set to false, or the files in `src` should be included in the `npm publish` tarball
https://github.com/holochain/holochain-client-js/blob/fb6d298e7d440082eb079c28913773735a709c7f/tsconfig.json#L6

The actual installed files are missing the `src` folder
<img width="255" alt="Screen Shot 2022-06-29 at 8 13 17 AM" src="https://user-images.githubusercontent.com/1409121/176472285-b262eecf-39c8-4be7-ba39-dc21cd9c7469.png">

**Comment by Connoropolous** [comment]
cc @jost-s

**Comment by jost-s** [comment]
I see the source maps in the npm package, this should be resolved.

**Comment by Connoropolous** [comment]
This is still ongoing... here's a screenshot:

<img width="780" alt="Screenshot 2023-01-14 at 6 50 00 PM" src="https://user-images.githubusercontent.com/1409121/212520384-a9eb3085-b529-4eec-9e8d-cddaa3635b91.png">

This is when using webpack 5 and a vanilla setup of create-react-app

`npx create-react-app my-app`
`cd my-app`
`npm install @holochain/client@0.11.10`
`npm start`

**Comment by jost-s** [comment]
I see some CommonJS-iness there, might that be a factor of the problem?

**Comment by jost-s** [comment]
What is also confusing is that it looks for source maps although the package is not even referenced in the code.

**Comment by jost-s** [comment]
The paths to the source maps were wrong. But even with the right paths I get some weird relative path duplication
```sh
WARNING in ../../holochain-client-js/lib/api/admin/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/jost/Desktop/holochain/holochain-client-js/lib/api/admin/api/admin/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/jost/Desktop/holochain/holochain-client-js/lib/api/admin/api/admin/index.ts'
```

Also there is an issue around this source map warning https://github.com/facebook/create-react-app/issues/11924.

I'm tempted to remove source maps altogether. What do you think?

**Comment by Connoropolous** [comment]
perhaps this is occurring: 
```
https://github.com/facebook/create-react-app/issues/11924#issuecomment-1016947373
```
we could go and look in the resulting folder on the filesystem for the actual source maps.

**Comment by jost-s** [comment]
The actual source maps are there, but the `.ts` files are not included.

**Comment by Connoropolous** [comment]
I believe that's the issue. There are different kinds of source maps, and I think the ones in use refer to the original TS files

**Comment by jost-s** [comment]
Yes, I see. I was thinking that the source map links the d.ts files and the .js files, but that wouldn't allow for exact lines during debugging.

Personally I don't use source maps for debugging, and I couldn't find an NPM package easily that includes them. Given that it hasn't been working all along no one has requested them. What is your sense, do you prefer to have source maps?

**Comment by Connoropolous** [comment]
the js code is reasonably readable, given that it doesn't change from the typescript a whole lot. maybe you're right and it's fine, just remove them
