### ISSUE TITLE
node:x imports trigger build errors for users of webpack/create-react-app who depend on this

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-client-js#116]
As-of, version 0.4.0 - 0.4.3 of this library

It "technically" succeeds at compiling, but it is also being thrown as an error

https://github.com/holochain/holochain-client-js/blob/69643e69b225d51084a8f9ee048ff05b21c1d2d0/src/bundle.ts#L12-L15

I am not sure but I hope there's a way to build this library without the nodejs dependencies. 
Otherwise, those of us who use webpack5 which is probably half of webjs coders I'd say, due to create-react-app, will have to follow some kind of hacky override path like this: 
https://thealiraza.medium.com/how-to-set-up-web3-js-with-react-18-and-webpack5-without-2228a5f4626f

First logged internally for hREA project here: https://github.com/h-REA/hREA/issues/315

Apparently the issue is widespread... https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5

**Comment by Connoropolous** [comment]
@guillemcordoba seeing anything like this also? I did see you put in a PR for a fix with the node prefix, but it introduced a differently layer to the issue.

cc @jost-s

**Comment by jost-s** [comment]
@Connoropolous This bundle module was introduced recently as a convenience. Funny, Timo reported that it compiled fine with webpack https://github.com/holochain/holochain-client-js/pull/101#issuecomment-1023661603.

I'll need to test this myself in order to confirm.

**Comment by Connoropolous** [comment]
seems to be a difference between webpack 4 and webpack 5. This link discusses that: https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5

**Comment by Connoropolous** [comment]
@jost-s (and cc @timotree3 because this relates to this feature that you introduced) 
we have, for hREA, needed to fork this project in order to publish a temp version that we can use, that doesn't include the nodejs imports. We are bundling with webpcak 5, which is the default for create-react-app and many other projects now. 

I am hoping that maybe we can work on coming to a consensus about what to do here. 

My proposal: since this library should very much be client-side/browser friendly, I propose to remove the code which was introduced specifically for nodejs. From my reading of it, the same thing could easily be handled *outside* of this library and the agnostic code could be called. What do you think?

**Comment by jost-s** [comment]
I am in favor of this suggestion. I too think that this code can be added to another library which is focusing on node development with the holochain client.

**Comment by Connoropolous** [comment]
cool. @timotree3 are you still active on the code that utilizes this code that you introduced in the PR https://github.com/holochain/holochain-client-js/pull/101 ? 
Otherwise maybe we need to pull in @robbiecarlton or @JettTech to ask about this

**Comment by zippy** [comment]
> cool. @timotree3 are you still active on the code that utilizes this code that you introduced in the PR #101 ? Otherwise maybe we need to pull in @robbiecarlton or @JettTech to ask about this

I don't believe that @timotree3 is active on this.   Also, turns out that I need this to be working for another react base project to work, so there's more call for resolving this.

**Comment by Connoropolous** [comment]
If you need a quick fix you can temporarily point to my fork

@sprillow-connor/holochain-client

There are versions 0.4.3 and 0.6.0 equivalents there with fixes

**Comment by robbiecarlton** [comment]
This is the first time I'm looking at this code, so take my input with a grain of salt but:

Just did a quick search of holochain and holo-host github orgs, and I'm not finding any other code that calls `appBundleWithProperties` or `readAppBundleFromPath `.

Given that, I think it's pretty safe to just remove this code entirely. 

If we want to also create a utility that provides this functionality for node users we can do that. Without input from @timotree3 about what he needed this for, I don't think that second part needs to be a priority.

**Comment by jost-s** [comment]
@robbiecarlton @Connoropolous @zippy I [removed `bundle.ts`](#125) and made a [release as  v0.7.0](https://github.com/holochain/holochain-client-js/releases/tag/v0.7.0).

**Comment by Connoropolous** [comment]
superb! we should be able to de-point from our fork and re-point at this, in our massive holochain .150 PR that's ongoing. 
https://github.com/h-REA/hREA/pull/340
