### ISSUE TITLE
during development seeing JSON.parse error due to launcher environment check

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-client-js#126]
In some cases, the fetch request to `.env-launcher.json` doesn't 404, and so it tries to parse the JSON. This leads to a confusing error being outputted to the console during development every time you import the @holochain/client . What would be better is for the `await env.json()` call to also be in a try/catch so that it can log a useful error when the response has been null. For my case, I am talking about create-react-app, but I'm guessing it affects others as well.

https://github.com/holochain/holochain-client-js/blob/2be891448ead17a6c9e299ae32a568afa90aa15b/src/environments/launcher.ts#L20

It's not fundamentally breaking because it gets caught, however, it's misleading and noisy
![Screen Shot 2022-08-07 at 11 17 56 AM](https://user-images.githubusercontent.com/1409121/183298069-eae07e14-95df-4ac2-a366-c5416ecd2587.png)
0

**Comment by Connoropolous** [comment]
Cc @guillemcordoba

**Comment by jost-s** [comment]
I've tried to wrap the error-causing call
https://github.com/holochain/holochain-client-js/blob/2be891448ead17a6c9e299ae32a568afa90aa15b/src/environments/launcher.ts#L17

in a `try..catch` block, but `catch` is never entered. Neither is this `.catch`
https://github.com/holochain/holochain-client-js/blob/2be891448ead17a6c9e299ae32a568afa90aa15b/src/environments/launcher.ts#L46

I couldn't figure out why and it's cumbersome to debug.

**Comment by jost-s** [comment]
@robbiecarlton FYI

**Comment by guillemcordoba** [comment]
Yeah I tried to catch the error in multiple ways without success... The issue I was having is that the browser will just throw and log an exception if a fetch fails, no matter if you try to catch it. In the next versions of the launcher we should try to do away with this fetch call... @matthme

**Comment by jost-s** [comment]
It works with the browser's own `fetch` call instead of cross-fetch. Doing away with it altogether is better still.

**Comment by matthme** [comment]
I could write the information to the window object instead. Would this be a better solution?

**Comment by jost-s** [comment]
IMO yes, definitely.

**Comment by matthme** [comment]
Okay great, then I'll add that additionally with the next launcher release and probably make a PR for the js-client at the same time.
