### ISSUE TITLE
AbbWebsocket.appInfo ignores installed_app_id

### ISSUE THREAD

**Issue by matthme** [holochain/holochain-client-js#128]
It seems that the `AppWebsocket.appInfo()` method ignores the required parameter `installed_app_id`.

## Steps to reproduce:
1. Create a hApp that creates an AppWebsocket like so
```
    const appWebsocket = await AppWebsocket.connect(
      `ws://localhost:${process.env.HC_PORT}`,
    );
``` 
and then calls the `.appInfo()` method on it with some random `installed_app_id`:
```
    const appInfo = await appWebsocket.appInfo({ installed_app_id: "SOME_random_APP_id" });
    console.log("appInfo: ", appInfo);
```
2. Install the app with an `installed_app_id` different than the one passed to `.appInfo()` above.
3. The console output will show the `installed_app_id` of step 2, i.e. of the app calling the method and not the one corresponding to the `installed_app_id` passed as an argument to `.appInfo()`.

## Remark:

It is definitely useful and important to have the option of getting the  `InstalledAppInfo` of the app calling the method without specifying the `installed_app_id` since the latter may have been arbitrarily chosen by the user and therefore cannot be known by the developer when writing the hApp. 
The current state of requiring an `installed_app_id` argument while ignoring it is however confusing.

**Comment by guillemcordoba** [comment]
Is this in the launcher environment?

**Comment by matthme** [comment]
Yes but also when running it in a sandbox during development.

**Comment by guillemcordoba** [comment]
Okey so if this happens in a sandbox environment it is certainly a bug. Beware we may be refactoring this API function and the calling mechanisms to it when signed zome calls are implemented throughout the stack.

**Comment by jost-s** [comment]
@matthme Thanks for the proper bug report.

I cannot reproduce this with @holochain/client@0.7.0. When I provide a nonexistent app id
```ts
const appInfo: AppInfoResponse = await client.appInfo({
    installed_app_id: "does not exist",
  });
  console.log("appinfo", appInfo);
```

I don't receive anything:
<img width="522" alt="image" src="https://user-images.githubusercontent.com/28270981/188178160-f961f72b-ffdc-49c0-b289-9b8e8fed6c21.png">

With the correct app id
```ts
const appInfo: AppInfoResponse = await client.appInfo({
    installed_app_id: NATIVE_INSTALLED_APP_ID,
  });
  console.log("appinfo", appInfo);
```

it outputs
<img width="514" alt="image" src="https://user-images.githubusercontent.com/28270981/188178362-9b829e84-094c-42aa-8009-f0eb9c392958.png">

Also when I run the e2e test of this repo and input a false app id, it behaves as expected.

The code looks fine https://github.com/holochain/holochain-client-js/blob/develop/src/api/app/websocket.ts#L90-L92. The only problem I can think of is that you have an app id override defined:
https://github.com/holochain/holochain-client-js/blob/develop/src/api/app/websocket.ts#L130-L134

**Comment by matthme** [comment]
Okay, I discovered ([this line](https://github.com/lightningrodlabs/we/blob/5696de94e12abe775d193f9e64a00c876828640b/ui/app/web-dev-server.config.mjs#L35)) in the `web-dev-server.config.mjs` that I wasn't aware of. I don't understand what this line does though to be honest, is it equivalent to specifying an `overrideInstalledAppId`? If I change the installed app id in that line to another id I get the expected behavior.
I didn't find any code otherwise where I would explicitly override the installed app id through the `@holochain/client` API.

**Comment by matthme** [comment]
To be precise, if I change the line in the `web-dev-werver-config.js` I always get appInfo null. The behavior I described in the issue appears if the app id specified in the `hc s` command [here](https://github.com/lightningrodlabs/we/blob/5696de94e12abe775d193f9e64a00c876828640b/package.json#L13) and the one in in the `web-dev-server.config.mjs` are equal.

**Comment by jost-s** [comment]
@matthme You're running into this https://github.com/holochain/holochain-client-js/blob/abe46453edcccb777ac97d6a317dac5eea2772d6/src/api/app/websocket.ts#L68-L72.

Try your test in a clean env without env vars and it'll work as expected.

**Comment by matthme** [comment]
I see. That makes sense, thank you! I seem to be lacking some context about environment variables here.
