### ISSUE TITLE
Error when running with Angular

### ISSUE THREAD

**Issue by var-che** [holochain/holochain-client-js#129]
Hi
I was trying to connect holochain client with my Angular 14 service with Ionic Framework, and during the compilation time of my code, I got this message:

```
[ng] Error: node_modules/@holochain/client/lib/api/client.d.ts:2:8 - error TS1259: Module '"/home/vlada/Documents/ionicapp/notus/notus/node_modules/isomorphic-ws/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
[ng] 
[ng] 2 import Websocket from "isomorphic-ws";
[ng]          ~~~~~~~~~
[ng] 
[ng]   node_modules/isomorphic-ws/index.d.ts:8:1
[ng]     8 export = WebSocket
[ng]       ~~~~~~~~~~~~~~~~~~
[ng]     This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
[ng] 
[ng] 
[ng] 
```

Any idea why this is happening?

**Comment by jost-s** [comment]
Without seeing the code, I can only surmise it's got to do with what the error says. Look here https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports and check your tsconfig.json.

**Comment by var-che** [comment]
Yes, that is a way to fix the error. It's about those exports.
