### ISSUE TITLE
Deleting cloned cell fails

### ISSUE THREAD

**Issue by matthme** [holochain/holochain-client-js#138]
Deleting a cloned cell after having it archived fails although it should definitely exist.

I made a minimal reproducible repo here: https://github.com/matthme/clone-test
The relevant lines of code are [here](https://github.com/matthme/clone-test/blob/main/ui/src/holochain-app.ts).

The error I'm getting:
```
Conductor returned an error while using a ConductorApi: AppError(CloneCellNotFound(CloneId(CloneId(\"clones.0\"))))
```

**Comment by jost-s** [comment]
Hi Matthias, thanks for the reproduction. The `role_id` argument of the call `deleteArchivedCloneCells` is wrong. You're specifying the clone id, when the DNA's role id is required. That call deletes all archived clone cells for a role id, not a specific clone cell.

We can improve the docs and also the error message.

**Comment by jost-s** [comment]
your test code works like this

```js
// creating cloned cell
    console.log("Creating cloned cell.")
    await this.appWebsocket.createCloneCell({
      app_id: 'clone-test',
      role_id: 'clones',
      modifiers: {
        network_seed: 'some_seed',
      },
    });

    if (cloneCellId) {
      await this.appWebsocket.archiveCloneCell({app_id: "clone-test", clone_cell_id: "clones.0" });
      await adminWebsocket.deleteArchivedCloneCells({app_id: "clone-test", role_id: "clones" });
    }
```

**Comment by matthme** [comment]
Oh I see. I was expecting to be able to delete cloned cells on an instance basis instead of all of them at once since that's what I need in my case (each clone is a We group and I want to be able to only delete a specific group).

**Comment by jost-s** [comment]
Then you need to archive the ones you want to delete and call `deleteArchivedCloneCells`.

**Comment by matthme** [comment]
Oh you're right, I can already do all I need.

**Comment by jost-s** [comment]
Great!

**Comment by jost-s** [comment]
And always feel invited to reach out, I'm just a message away =)
