### ISSUE TITLE
Change role_id to role_name to align with HC v0.0.175

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain-client-js#141]
I would also make sure that all the other renames are checked: https://github.com/holochain/holochain/blob/develop/CHANGELOG.md#holochain-00175

**Comment by jost-s** [comment]
closed by [2f5807cbaeb27c7a15d0bd745464fd53058bac4d](https://github.com/holochain/holochain-client-js/commit/2f5807cbaeb27c7a15d0bd745464fd53058bac4d)
