### ISSUE TITLE
0.11.11 reintroduces bundling issues due to `node` package prefix

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-client-js#162]
This is when using webpack 5 and a vanilla setup of create-react-app

`npx create-react-app my-app`
`cd my-app`
`npm install @holochain/client@0.11.11`
(add a line of code to import anything from @holochain/client)
`npm start`

<img width="1154" alt="Screenshot 2023-01-15 at 10 38 22 AM" src="https://user-images.githubusercontent.com/1409121/212560375-fdab0bdf-2667-4ea0-aeab-0d098a780168.png">

**Comment by jost-s** [comment]
Fairly lame, this webpack 5!

**Comment by Connoropolous** [comment]
yar. It is possible that the 'bleeding edge' settings in the tsconfig file for this repo of `ESNext` and `ESNext` in this repo are very aggressive in terms of lacking backwards compatibility

**Comment by jost-s** [comment]
They are avantgarde indeed. I shall tone it down a notch.
The `node` schema imports have been around since Node v16.0.0, that is not particularly bleeding. ;-)

I'll release a fix for this next week with the Holochain rc3 release. Unless you have urgency to have this fixed sooner.

**Comment by jost-s** [comment]
fixed by #163
