### ISSUE TITLE
Building with Vite throws error because of `ws` import

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain-client-js#164]
Building an app that depends on @holochain/client with `vite build` gives this error: 
```
../node_modules/@holochain/client/lib/api/client.d.ts:1:23 - error TS2688: Cannot find type definition file for 'ws'.

1 /// <reference types="ws" />
                        ~~

../node_modules/isomorphic-ws/index.d.ts:6:28 - error TS7016: Could not find a declaration file for module 'ws'. '/home/guillem/forum/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

6 import WebSocket = require('ws')
                             ~~~~
```

This is fixed by installing the `@types/ws` package, but if this is the case maybe the client itself should declare it in its own dependencies (not devDependencies because those won't get installed by downstream packages).

**Comment by jost-s** [comment]
I haven't been able to reproduce it in a minimal Vite TS project https://stackblitz.com/edit/vitejs-vite-dc78yv?file=src%2Fmain.ts

**Comment by jost-s** [comment]
Is this still an issue for you, @guillemcordoba?
