### ISSUE TITLE
CellProvisioning types are off

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-client-js#165]
From experience, it works not like described in the typescript, but like this:
https://github.com/h-REA/hREA/blob/75ba44b16a65d1257cd82fc472c5fe8167b9aedc/test/init.js#L129

https://github.com/holochain/holochain-client-js/blob/cdcf8496811817f06d96cea471db90890602bd27/src/api/admin/types.ts#L153-L177

it's because of this line of code:
https://docs.rs/holochain_types/0.1.0-beta-rc.1/src/holochain_types/app/app_manifest/app_manifest_v1.rs.html#162

**Comment by jost-s** [comment]
Thanks for reporting!
