### ISSUE TITLE
Serialization issues because of Javascript Number type

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain-client-js#2]
@maackle 
When trying to callZome with a number properly, than has to translate to an u64 or f64 on the WASM side, I found edge cases that caused holochain to not be able to deserialize the parameters properly. These edge cases are:

- With a big integer (like Javascript's `Date.now()`) that isn't over 64 bits. Msgpack cannot translate it properly since it is sent as a float over the wire, I think because Javascript number only can contain 53 bits of numbers.
- With floats than happen to have no decimals (eg: 1.0). This is sent over the wire as an integer, so the WASM side cannot deserialize it into f64.

I think the fundamental issues are described very well here: https://www.npmjs.com/package/msgpack-typed-numbers#typed-numbers.

Although I don't know if the fix should be made on this library or on the receiving end, looks like it's the JS client the one that's misinterpreting things.

**Comment by guillemcordoba** [comment]
This isn't blocking me, as I have this as workaround: 
```rust

#[serde(untagged)]
#[derive(Serialize, Deserialize, Debug, SerializedBytes, Clone)]
pub enum Number {
    Float(f64),
    Integer(u64),
}
```

Which is a rust type that can receive either floats or integers. Granted, this isn't ideal, but will work for now.

**Comment by maackle** [comment]
@guillemcordoba I know that @thedavidmeister intended that we'd never serialize a primitive value over the wire, so this is kind of expected, and something like your workaround is what I'd recommend. However, it is a problem that there isn't a better error for visibility into this, which is something that would be good add. So I'll let this issue track that problem.

**Comment by thedavidmeister** [comment]
@guillemcordoba this is intended behaviour

serialization doesn't preserve type information across contexts (e.g. different languages) and there's no guarantee that any particular primitive in a serialized format exists at the receiving end - (the lack of) javascript number types show the problem well

by forcing new types at the boundaries we make (de)serialization behaviour explicit

it might feel a bit awkward and verbose at times but it does make things safer

**Comment by maackle** [comment]
@guillemcordoba note that this is no longer the case: zome functions can accept primitive types (or soon will)

**Comment by guillemcordoba** [comment]
Oh really? Didn't think that that change would affect the serialization weirdness. Will try, thanks!
