### ISSUE TITLE
If I wanted to use holochain 0.1.6, which version of holochain-client-js would I use?

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-client-js#204]
People are requesting a version of Acorn bundled with holochain 0.1.6, but I depend on holochain-client-js APIs, and I have no idea how to tell which one would be compatible.

**Comment by Connoropolous** [comment]
@jost-s @guillemcordoba @matthme can you advise?

**Comment by jost-s** [comment]
Sure, it's [v0.12.5](https://github.com/holochain/holochain-client-js#installation).

**Comment by Connoropolous** [comment]
ah! thankyou
