### ISSUE TITLE
`CreateLink` is missing link type field

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain-client-js#218]
This is the rust type: https://github.com/holochain/holochain/blob/13b230877e706f8d31f4ac33e6bfa01130cef442/crates/holochain_integrity_types/src/action.rs#L515

This is the typescript type: https://github.com/holochain/holochain-client-js/blob/ca95b0b6db6a1c70c810e4f66403d834098c1393/src/hdk/action.ts#L100

**Comment by jost-s** [comment]
fixed in v0.17.0-dev.2
