### ISSUE TITLE
Decouple js client from host specific zome call signing logic

### ISSUE THREAD

**Issue by matthme** [holochain/holochain-client-js#221]
Currently the js-client has host specific zome call signing logic for both tauri and electron. I think it would make sense to decouple that, i.e. that the js client does not need to care about the specifics of the host that does the signing but can instead just check for a variable on the window object and have it signed that way. Along the lines of:
```
if (window.__HOST_ZOME_CALL_SIGNER__) {
  signedZomeCall = await window.__HOST_ZOME_CALL_SIGNER__.signZomeCall(payload);
}
```
The host (tauri/electron/...) is then responsible for providing that method on the window object.
We can still keep the current methods as a fallback for backwards compatibility.

I can put up a PR for this if people agree.

cc @jost-s @mattyg

**Comment by mattyg** [comment]
Yep that sounds good!

**Comment by jost-s** [comment]
Sweet as!
