### ISSUE TITLE
appInfo request returns `null` if app not found

### ISSUE THREAD

**Issue by matthme** [holochain/holochain-client-js#232]
According to the function signature of `AppWebsocket.appInfo` I expect to get a `Promise<AppInfo>`, i.e. that the call would fail if there is no app installed with the given `installed_app_id`. However if there is no app installed with the given id the call succeeds and returns `null`. Either this should be documented in the function signature (i.e. `Promise<AppInfo | null>`) or the Promise should reject.

**Comment by jost-s** [comment]
Thanks for raising this.

The conductor returns an optional `AppInfo` indeed https://docs.rs/holochain_conductor_api/0.2.5/holochain_conductor_api/enum.AppResponse.html#variant.AppInfo

I'll see if I can bend the client code to use `AppInfo | null` : )
