### ISSUE TITLE
Automatically try re-establishing connection if socket is closed

### ISSUE THREAD

**Issue by matthme** [holochain/holochain-client-js#271]
If sockets close, e.g. due to sleep mode of one's laptop, it would be nice if the js-client would automatically attempt to re-establish the connection with the connection options as supplied for the initial connection before [throwing](https://github.com/holochain/holochain-client-js/blob/16aa191c04974351377426c7f0ffd9f8893779d4/src/api/client.ts#L216) an `Error: Socket is not open`.

Apparently this logic was already implemented at some point but [got removed](https://github.com/holochain/holochain-client-js/commit/8253f559f20f247c4cefaf32bb4d86882766b8ae#diff-b8947d6beda79d7ac4e7fbaf1da6b81f496c35e8f87635fc0b15599ee8dd0478L209-L228) a while ago.

**Comment by jost-s** [comment]
fixed by #193
