### ISSUE TITLE
`cap_secret` and `payload` params for `AppCallZomeRequest` can be optional

### ISSUE THREAD

**Issue by c12i** [holochain/holochain-client-js#286]
Currently, you need to set these param values to `null` to statisfy the typescript compiler. I think making them optional would be a better solution

```ts
 const links: Link[] = await client.callZome({
   cap_secret: null, // make optional
   role_name: "forum",
   zome_name: "posts",
   fn_name: "get_all_posts",
   payload: null, // make optional
 });
```

**Edit**
On top of this, I think it might be worth removing the `provenance` param from `AppCallZomeRequest` since it would get overridden anyway:

https://github.com/holochain/holochain-client-js/blob/16aa191c04974351377426c7f0ffd9f8893779d4/src/api/app/websocket.ts#L345

**Comment by jost-s** [comment]
Actually it's not always overridden, just when a `role_name` is used as cell address instead of a cell_id.

Nevertheless it can just be made optional.

**Comment by jost-s** [comment]
The thing is that the provenance always gets overridden if it's not an already signed zome call, in which case it's only serialized bytes and signature anyway. So it doesn't make sense to keep the provenance in.
