### ISSUE TITLE
Rename repo to make clear that this is a JS implementation

### ISSUE THREAD

**Issue by maackle** [holochain/holochain-client-js#50]
Perhaps `js-conductor-api`?

**Comment by nphias** [comment]
i see .ts files in the source.... hasnt this been done ES6+ typescript.. ?

**Comment by maackle** [comment]
The compilation target is still JS.

I just want to differentiate it from API bindings which could eventually be written in other languages, e.g. Python.

**Comment by zippy** [comment]
If we go the way @guillemcordoba went [here](https://github.com/holochain/conductor-client-rust) we should rename it to `conductor-client-js`

**Comment by zippy** [comment]
or maybe even drop conductor and use `holochain-client-js`

**Comment by jost-s** [comment]
done
