### ISSUE TITLE
All zomeCalls on a particular WS connection timeout after Lair timesout on zomeCall once

### ISSUE THREAD

**Issue by zo-el** [holochain/holochain-client-js#55]
I have attached a PR that can be run to test out this bug.

**Scenario:**
- Agent connects to app WebSocket (let's call it `appWS`) 
- Agent make a zomeCall using `appWS` and holochain requests lair for a signature
- Lair times-out and holochain-conductor-api timeouts with its inbuilt timeout.
- Using the same `appWS` instance connection we make a new zomeCall 
- Now it looks like the zomeCall does not reach holochain and it just times-out.

To reproduce this  scenario I have a shim that holochain uses to timeout when we need it to so that we can reproduce this bug
 
 > Note: This Could also be a bug in holochain.

**Comment by zo-el** [comment]
Here is the PR with a failing test: https://github.com/holochain/holochain-conductor-api/pull/56

**Comment by jost-s** [comment]
Closing this as discussed on the PR. Please re-open or create a new issue if it happens again.
