### ISSUE TITLE
Switch to @msgpack/msgpack?

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain-client-js#6]
Hi @maackle ,

I'm trying to build my first UI using rollup, and it's not compiling due to this issue: https://github.com/kawanet/msgpack-lite/issues/91. And that led me to see that the code for msgpack-lite hasn't been updated in 4 years.

Is there some reason not to use https://github.com/msgpack/msgpack-javascript? Bundle size seems similar, and it seems well supported.

**Comment by maackle** [comment]
@guillemcordoba no reason at all, msgpack-lite was just the first thing I found that worked. If you can easily get it working with that, feel free to make a PR, or someone else will soon

**Comment by guillemcordoba** [comment]
I have it working on my machine, will make a PR when I can.

**Comment by guillemcordoba** [comment]
Opened https://github.com/holochain/holochain-conductor-api/pull/8
