### ISSUE TITLE
Buffer not defined error for [ webpack ES6 fix ]

### ISSUE THREAD

**Issue by nphias** [holochain/holochain-client-js#62]
using 03-23/msgpack branch to fix the webpack/ES6 issues
i still get this error:

core.js:6162 ERROR Error: Uncaught (in promise): ReferenceError: Buffer is not defined
ReferenceError: Buffer is not defined
    at Object.input (app.js:52)
    at common.js:19
    at Generator.next (<anonymous>)
    at common.js:8
    at new ZoneAwarePromise (zone-evergreen.js:1387)
    at push.IEn3.__awaiter (common.js:4)
    at AppWebsocket.callZome (common.js:18)

**Comment by nphias** [comment]
This issue is webpack related.. 'buffer' being a non-browser nodejs function
in a webpack.config.js add the foillowing lines:

module.exports = {
  ...
  node: {
    Buffer: true
  }
}

if you would rather not use a webpack config
you can use polyfills.ts to add it to global space
in polyfills.ts:
(window as any).global = window;
global.Buffer = global.Buffer || require('buffer').Buffer;

followed by:
  npm install buffer

**Comment by nphias** [comment]
re-opening for reference to others having the issue

**Comment by jost-s** [comment]
@nphias I don't understand under which circumstances the error happens. Please provide some steps to reproduce and what the expected behavior then should be.

**Comment by nphias** [comment]
oh right .. yes i havent had to do that hack anymore so can assume it was fixed

**Comment by jost-s** [comment]
@nphias Ah Thomas, this is you! 😀 Cool, thanks
